server:
  port: 10010
spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka

zuul:
  prefix: /api #  添加路由前缀
  routes:
    item-service: /item/**

    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false #访问service时候加上upload前缀

hystrix:
  command:
    default:
      execution:
        isoiation:
          thread:
            timeoutInMilliseconds: 5000
#            熔断时长5s
ribbon:  #负载均衡
  ConnectTimeout: 1000 # ribbon链接超时时长
  ReadTimeout: 3500 # ribbon读取超时时长
  MaxAutoRetries: 0 # 当前服务重试次数
  MaxAutoRetriesNextServer: 0 # 切换服务重试次数

