server:
  port: 8082
spring:
  application:
    name: upload-service

  servlet:
    multipart:
      max-file-size: 5MB #限制上传文件大小

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true